################################################################################
#                                                                              #
#                                                                              #
#   This file contains all global parameters used in the analysis functions    #
#                                                                              #
#                                                                              #
################################################################################


#Absolute path to experiment folder. This folder should contain all sample
#folders (Those beginning with 5...)
ABS_PATH_EXPERIMENT = ""

#Paths of the scoring files within the output directory of a sample
#(The one with all the outputs)
RAW_SCORES_RELATIVE_PATH = "competition/rawScores.csv"
EVENTS_RELATIVE_PATH = "outputEvents.xml.gz"
SUBMISSION_SCORE_RELATIVE_PATH = "competition/SubmissionScores.csv" #Deprecated

#Input type: used by the sample loader to parse the correct inputs
INPUT_TYPE = "CIRLCE_EXP"
#INPUT_TYPE = ROAD_PRICING_EXP

